// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Jensen_Final.Models
{
    public partial class DriversLicense
    {
        public int DriversLicenseId { get; set; }
        public string DriversLicenseNumber { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string StreetAddress { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public DateTime? DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string EyeColor { get; set; }
        public string Height { get; set; }
        public int? Weight { get; set; }
        public string Class { get; set; }
        public int? DonorIsChecked { get; set; }
        public DateTime? DateIssued { get; set; }
        public DateTime? DateExpires { get; set; }
    }

    public class Drivers_License_Number_Check
    {
        public void DriversLicenseNumberCheck() { }
    }
}