// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Jensen_Final.Models
{
    public partial class Driver
    {
        public int DriverId { get; set; }
        public string DriversLicenseNumber { get; set; }
        public string Ssn { get; set; }
    }

    public class SSN_Check
    {
        public void SSNCheck() { }
    }
}