// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Jensen_Final.Models
{
    public partial class DriverVehicle
    {
        public int DriverVehiclesId { get; set; }
        public int? DriverId { get; set; }
        public int? VehicleId { get; set; }
    }
}